format = """
[](bg:#282a36 fg:#282a36)\
$directory\
[](fg:#282a36)\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#282a36"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#282a36"
format = '[[($all_status$ahead_behind)](fg:#f0f0f0 bg:#282a36)]($style)'

[nodejs]
symbol = ""
style = "bg:#282a36"
format = '[[ $symbol ($version) ](fg:#f0f0f0 bg:#282a36 )]($style)'

[rust]
symbol = ""
style = "bg:#282a36"
format = '[[ $symbol ($version) ](fg:#f0f0f0 bg:#282a36 )]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#282a36 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#282a36"
format = '[[ $symbol ($version) ](fg:#282a36 bg:#212736)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#282a36"
format = '[[  $time ](fg:#a0a9cb bg:#1d:2230)]($style)'
